name: Build and publish Docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Log in to Docker registry
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} \
            | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get clin version
        id: get_version
        run: |
          echo "::set-output name=version::$(cat requirements.txt | grep clin== | cut -d= -f3)"

      - name: Check if the version tag already exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check_version_tag
        with:
          tag: ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t clin:latest .

      - name: Create release
        uses: actions/create-release@v1.1.4
        if: ${{ github.ref == 'refs/heads/master' && steps.check_version_tag.outputs.exists == 'false' }}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          body: https://github.com/zalando-incubator/clin/releases/tag/${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Tag Docker image
        run: |
          docker tag clin:latest dstockhammer/clin:latest
          docker tag clin:latest dstockhammer/clin:${{ steps.get_version.outputs.version }}

      - name: Push Docker images
        if: ${{ github.ref == 'refs/heads/master' && steps.check_version_tag.outputs.exists == 'false' }}
        run: |
          docker push dstockhammer/clin:latest
          docker push dstockhammer/clin:${{ steps.get_version.outputs.version }}
